name: Auto Merge to cf-pages

on:
  push:
    branches:
      - master

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

